import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext.tsx';
import { api } from '../../services/api.ts';
import { PaymentRequest } from '../../types.ts';
import {
  CreditCard,
  Search,
  CheckCircle2,
  ExternalLink,
  ShieldCheck,
  Zap,
  DollarSign,
  AlertCircle,
  Copy,
} from 'lucide-react';

export const PaymentsView: React.FC = () => {
  const { activeBusiness } = useAuth();
  const [payments, setPayments] = useState<PaymentRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [simulating, setSimulating] = useState(false);
  const [simulatedId, setSimulatedId] = useState<string | null>(null);

  const businessId = activeBusiness?.id || 'biz_aura_001';

  const loadPayments = async () => {
    try {
      setLoading(true);
      const data = await api.getPayments(businessId);
      setPayments(data);
    } catch (err) {
      console.error('Failed to load payments:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPayments();
  }, [businessId]);

  const handleSimulatePayment = async (pay: PaymentRequest) => {
    try {
      setSimulating(true);
      await api.simulatePaymentSuccess(businessId, pay.orderId, pay.id);
      setSimulatedId(pay.id);
      loadPayments();
      setTimeout(() => setSimulatedId(null), 3500);
    } catch (err) {
      console.error('Failed to simulate payment:', err);
    } finally {
      setSimulating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-2xl bg-slate-900 border border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <CreditCard className="w-5 h-5 text-emerald-400" />
            <h1 className="text-lg font-bold text-white">Payment Requests & Checkout Gateways</h1>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Omnichannel payment links generated by your AI employee with server-side webhook verification and fraud protection.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <span className="px-3 py-1.5 rounded-xl bg-slate-800 border border-slate-700 text-slate-300 font-mono">
            Provider: Stripe & Paystack Ready
          </span>
        </div>
      </div>

      {/* Payment Gateway Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[
          { name: 'Stripe Global', status: 'Connected', desc: 'Credit cards, Apple Pay, Google Pay, Klarna' },
          { name: 'PayPal Commerce', status: 'Available', desc: 'PayPal balance, Venmo, Pay in 4' },
          { name: 'Paystack Africa', status: 'Connected', desc: 'Direct bank transfer, mobile money, cards' },
        ].map((gw, idx) => (
          <div key={idx} className="p-4 rounded-2xl bg-slate-900 border border-slate-800 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between">
                <span className="text-sm font-bold text-white">{gw.name}</span>
                <span className="text-[10px] font-semibold px-2 py-0.5 rounded bg-emerald-500/15 text-emerald-400 border border-emerald-500/20">
                  {gw.status}
                </span>
              </div>
              <p className="text-xs text-slate-400 mt-1">{gw.desc}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Transactions Table */}
      <div className="rounded-2xl bg-slate-900 border border-slate-800 overflow-hidden">
        <div className="p-4 border-b border-slate-800 bg-slate-950/60 flex items-center justify-between">
          <h3 className="text-sm font-bold text-white">Generated Payment Requests</h3>
          <span className="text-xs text-slate-400">Transactions count: {payments.length}</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-950/40 border-b border-slate-800 text-[10px] font-semibold text-slate-400 uppercase tracking-wider">
              <tr>
                <th className="px-4 py-3">Order / Txn Ref</th>
                <th className="px-4 py-3">Customer</th>
                <th className="px-4 py-3">Amount</th>
                <th className="px-4 py-3">Gateway</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3 text-right">Webhook Simulation</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {payments.map((p) => {
                const isPaid = p.status === 'completed';
                return (
                  <tr key={p.id} className="hover:bg-slate-800/30 transition-colors">
                    <td className="px-4 py-3 font-mono">
                      <div className="font-bold text-white">{p.orderId}</div>
                      <div className="text-[10px] text-slate-400">{p.transactionRef}</div>
                    </td>
                    <td className="px-4 py-3 font-medium text-white">{p.customerName}</td>
                    <td className="px-4 py-3 font-mono font-bold text-emerald-400 text-sm">
                      ${p.amount.toFixed(2)} {p.currency}
                    </td>
                    <td className="px-4 py-3 capitalize text-slate-300">{p.provider}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
                          isPaid
                            ? 'bg-emerald-500/20 text-emerald-300'
                            : 'bg-amber-500/20 text-amber-300'
                        }`}
                      >
                        {p.status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-right">
                      {isPaid ? (
                        <span className="text-emerald-400 font-semibold text-[11px] flex items-center justify-end gap-1">
                          <ShieldCheck className="w-4 h-4" /> Webhook Confirmed
                        </span>
                      ) : (
                        <button
                          onClick={() => handleSimulatePayment(p)}
                          disabled={simulating}
                          className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow-sm transition-all active:scale-95 disabled:opacity-50"
                        >
                          Simulate Verified Payment
                        </button>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
